# this is a comment
[group1]
  key_string = "A"
  key_float = 123.456
  key_int = 789
  key_int_array = [1, 2, 3]

[group2]
  key_string = "B"
  key_float = 789.012
  key_int = 345
  key_int_array = [4, 5, 6, 7, 8]
